### ISSUE TITLE
uninitialized constant WorldDb::Model::Region (NameError)

### ISSUE THREAD

**Issue by ramthakur1991** [worlddb/world.db.models#2]
Hi @geraldb ,

I'm try to run the `rake db:create` or `rake db:migrate` command I'm getting the following error .

Ruby Version is : 2.3.0 
Rails Version is : 5.0.0.1
Bundler version is : 1.13.2

Can you suggest how do i get fix this error to get the beer.db and world.db ?

Thanks 
![screenshot from 2016-10-06 12 11 26](https://cloud.githubusercontent.com/assets/9669494/19142842/08d00856-8bbe-11e6-92f9-2733bd0bf819.png)

**Comment by geraldb** [comment]
@ramthakur1991 Welcome to world.db (and beer.db). Please send (setup/installation) questions to the [forum / mailing list](http://groups.google.com/group/openmundi). Thanks. Cheers.
